all:
	gcc -c Productores.c funciones.c funciones2.c
	gcc Productores.o funciones.o funciones2.o -o Productores
	gcc -c Consumidores.c funciones.c funciones2.c
	gcc Consumidores.o funciones.o funciones2.o -o Consumidores
