all:
	gcc -c mercado.c -lncurses -g3
	gcc -c funciones.c -lncurses -g3
	gcc -c funciones2.c -lncurses -g3
	gcc -c TADColaEst.c -lncurses -g3
	gcc mercado.o funciones.o funciones2.o TADColaEst.o -lncurses




