all:
	gcc -c -g3 banco.c -lncurses 
	gcc -c -g3 funciones.c -lncurses
	gcc -c -g3 funciones2.c -lncurses
	gcc -c -g3 funciones3.c -lncurses
	gcc -c -g3 TADColaDin.c -lncurses
	gcc banco.o funciones.o funciones2.o funciones3.o TADColaDin.o -lncurses
